### ISSUE TITLE
How to load Cloud CP/M with this code?

### ISSUE THREAD

**Issue by snhirsch** [nabunetwork/Adaptor#2] opened 2023-06-07 15:47 UTC
I'm having persistant communication issues when running the Internet adapter from nabu.ca, while this one appears to work just fine.  Is there any way to point this at the Cloud CP/M server?  I admit to being very confused as to why there appears to be multiple disjoint efforts.

**Comment by seanrox** [comment] 2023-06-07 22:52
The NabuNetwork.com software does not support DJ's CloudCPM. The Nabu.ca software is closed source. We use the wonderful open source Ishkur to power all things CP/M. We will have a  v2.1 update released in the coming days. If you want Ishkur to work with DJ's software, you will need to bring that up with him directly.

**Closed by seanrox** 2023-06-07 22:52 UTC

**Comment by snhirsch** [comment] 2023-06-07 23:59
I don't have any specific need for Nabu.ca software to support Ishkur.  I'm mainly trying to understand and learn the ecosystem in general.  From what I've seen so far, Ishkur is a more robust implementation and I'm willing to use whatever "adapter" can support it.  For example, I'm seeing regular lockups with Cloud CPM and the author simply tells me it's my cabling.  It's not.  I see no problems with any other applications and the issues are specific to files with more than one extent.  Your implementation works just fine.  

It would help me greatly if I understood how to build Ishkur from source and boot it under the open-source internet adapter.  If you can document the architecture and installation just a wee bit more I'll be glad to help with coding and/or debugging.  At this point it's a very steep learning curve.  I've been working with CP/M since 1983 and have strong Z80 assembly coding skills.

**Comment by seanrox** [comment] 2023-06-08 03:25
As you pointed out my NabuNetwork.com adapter software supports Ishkur which was done by design, however I do not offer support on how to compile Ishkur on my Github since I am not the author of the Ishkur CP/M software. I have done some minor tweaks to the NabuNetwork.com implementation of Ishkur, but those changes are being rolled into the main Ishkur branch. If you'd like any additional help with my adapter software, please reach out directly via the NabuNetwork.com contact page and we can discuss.

**Comment by snhirsch** [comment] 2023-06-08 18:59
Hi, Sean.  Unfortunately I'm not able to reach your contact page.  Firefox indicates the SSL cert is invalid for that particular domain.  How to best get in touch?

**Comment by seanrox** [comment] 2023-06-08 22:08
Hey Steven. The SSL cert issue is resolved as of a few hours ago. Please try again. Thanks!
